version: '2'
services:
  web:
    image: nevishs/5.6-apache
    volumes:
      - /tmp/DockerComposeLamp/www:/var/www/html
    links:
      - db:test
    ports:
      - 80:80

  db:
    image: nevishs/5.7-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: test

